{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "mysql-credentials",
    "namespace": "default",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "mysql-credentials",
        "namespace": "default",
        "creationTimestamp": null
      },
      "type": "Opaque",
      "data": null
    },
    "encryptedData": {
      "connection": "AgB+iuBnb/ZkR+2gVEgCKYyw0gb0Cx3/BbCorK9qRIJqQMf+S1Hu3v3YUtznXOKnk1wcLHilB6Lvb+ot1qqkjg2ue+F/hvgLFQeGvInWwbAsJrZdDWJFRjjsyLk3ao+2RL8MH17k16YNCLI0jRnFHs19EGACgXL6XsE+BrDEFsIFfeK49puOMqZavdlACoffiX6XXZKNNsLtqAAWRlNLy6qL164XF9yLZdcFTE1q+aPDqOCJdZvKT6ZKuXT+GVs/VnX8NyH52BxHKN4BpfG3isAAOXsr16X+rpm5nCJ2QkkDhwec0KMFPtgfk6Va6d4dLcwd0+kuK0BFZNiY5Zq/YhcINirPF6oLLthCrtO9QhU/41ohQeA0aX8L/uApC6MswPrLbfJWXnK/+5ZAagrKGfrPO3ZZgLICMV664aNUuxI3yZJs4+fdwYrr7tlhNIfOYk/dLp2hJmlXcCeBfLaEcXC0QNVZ1Y+feyG4nIT6kPnenv0lq4ZCBQgG2kTuImK7Mm0YBNmHecfjoZrBZ2MuESqfnQUCugfIY1pHZoYNXi7WKuhD4eZnmjcXZxgHLLTh2e8WB7O6zH3526rDuDDRtrhU3nzZu8mKFbuX+EKPlDx2BQL/mIlQP4yayNSWtmcCsQn0X4x0JyojusOlqgUqPNt1dsr38ppP7n3/tkYT2ZifyRaqhCIKduo7cf83YVSeEX61AuALjT2cy+VTFpFu34+iwCVwnzP1NSIAubGyviREnCM="
      "password": "AgCPkAwfwjxqG582UoO5icRDGmOHnKuhG8AinoeKji4y6QD/REFlwkC11OYPD1NdQycpQY4wZiKlF7Du3vSlzNMLq3yrTidtv7BeQDQYhb8RBBcrDXwDcUaA7Fr3/uGeOkZOG9xmeZxwcBnedoBb6MlKczaHaslMXmUB2oybJQTO+CyMZZgR0g4LH37tVQhKd/4fwJZEURlJsSVxbRyaaX+1XnUbTnFQSvw1L6TPMkWyoTepdUCzp4kTwpJMnupUcni04z10wUewn0ypVGDfTEeLAKe1XrL9PVZHUDRfG+r5VWcdmL+/AwNOipcWKP0YhMlsjfZoW1450DzJC6MsHpIQJb/U15GpXb8soW5GnTib1e91aFbogHXMtQoSZ/uPsWJvxeuaGoMMA8flyIYHdUmOtpCLAKZ0VG2B16/TW4blpLFYQ1L3c3TIffSTSt3II/LQLSGIuR3e69rLvmVcgN8eEzwXE1bRWKluBinr8btFFFLNarq3heJvWXwPPv9+86y59GB2+5RUjn8foby4ZDEamtowAChMzvCNDWM+ALiW23BjPsf2D0AK3ncM+30KgYfsulEes3tfax0CvTdgHsGMrurt228eyb0W7JbegDByGsiGgvVhROUbBf8nep2bUdu7mEDxka8CxqRhHfFN6gLz25LlCyfWL/Yi1qTcoWJfxKIxpE5bI/Nuatt5aebu0vEJvbafVZZVBfWeN+6sioQ="
      "username": "AgA0xuXWox1OAdOONu0WvFdHsXblSFCGa5Oo4Zsnfo3Y8x6BZUjApsmlhToGHk6HJA7Y4Xvm2h5g81VKTpNN9YBU/biOVCR5fzvjrPDq44Y8EBUBAdwnIcTdqcR46i9BEnwVADqtw+UM6Ng5a9nKEpOVnSltE02+A16MPsFw67UoDyYh5wyFqEMQsjUYBJhXHkxUhYkv4SW1W6MsuvucEvqxo4AktsM8ghtAfWPf2hhX013VIIymx5zMm+2WE+oLluZ5g9BuJvEMqbWWKV2s7jJI0rMnecyWEBLFFaSicxSDY/UAUQbpToGdgstZvAFw8RmMFXSS9D+22VxgTrOi+LYPREROYW0k8FmsOgkFX8Bz13nEZo9KNWRX2jMTOzfHK3zl9UKxaZIP9kXMjTvnjVz1A9VkInZkSjZ7B+4mNlqN/vSolh4UidKab2IoyWgAihhizfxN39l/Ha6CGrRT+9TqszMgf568IO9ShrpbPunb5I43GxtiJBa7B6rP/djq7NcbZ86KT/wk6wTmhhyFZQX5lLRU86TBy3C/3MsLu+1fu6E+c2sXAtvOr3rU/04Z+PhF45hlm+SZjviJy2ZL6pJiV56enMz4Y1mE8AroiiV+ru5RX0jUo26BzedWRaBosPq65lhNkeMX1FMNqPkFo28M/JRKU22a1nUWTRrMD++MldRfMFY+4HX7lsGbBwaUwezCf/2A+Ti8twb66Q=="
    }
  }
}
